# Generated by Django 5.2.9 on 2026-01-13 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='celular',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Este campo deve conter exatamente 11 números.', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Este campo deve conter exatamente 11 números.', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1),
        ),
    ]
