# Generated by Django 5.2.9 on 2026-01-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_client_name_alter_appointment_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
