# Generated by Django 5.2.9 on 2026-01-14 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_client_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client_phone',
        ),
    ]
